# --- !Ups

CREATE TABLE ROOMS (
    ROOM_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    ROOM_NAME VARCHAR2(255) NOT NULL,
    PRIMARY KEY (ROOM_ID)
);

CREATE TABLE USERS (
    USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    ACTOR_NAME VARCHAR2(255) NOT NULL,
    ACTOR_PATH VARCHAR2(255) NOT NULL,
    ROOM_ID BIGINT(20) NOT NULL,
    USER_NAME VARCHAR2(255) NOT NULL,
    JOIN_DATE TIMESTAMP NOT NULL DEFAULT SYSDATE,
    IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

# --- !Downs

DROP TABLE ROOMS;
DROP TABLE USERS;